# Generated by Django 5.2.10 on 2026-02-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('sem', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
