# Generated by Django 5.2.10 on 2026-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(choices=[(1, '1st sem'), (2, '2nd sem'), (3, '3rd sem'), (4, '4th sem')]),
        ),
    ]
