# Generated by Django 5.2.10 on 2026-02-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('specialization', models.CharField(max_length=60)),
                ('fee', models.FloatField()),
                ('accreditation', models.BooleanField(default=False)),
            ],
        ),
    ]
